services:
  - type: web
    name: stasya-chess
    env: node
    buildCommand: |
      chmod +x stockfish/stockfish
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: stockfish-data
      mountPath: /opt/render/project/src/stockfish
      sizeGB: 1
